<template><h1 id="reactmarker" tabindex="-1"><a class="header-anchor" href="#reactmarker" aria-hidden="true">#</a> ReactMarker</h1>
<h1 id="给-rn-摇一摇添加自定义工具" tabindex="-1"><a class="header-anchor" href="#给-rn-摇一摇添加自定义工具" aria-hidden="true">#</a> 给 RN 摇一摇添加自定义工具</h1>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>mReactInstanceManager = ((ReactApplication) application).getReactNativeHost().getReactInstanceManager();
mReactInstanceManager.getDevSupportManager().addCustomDevOption
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h1 id="获取rn-js线程并得到线程cpu时间" tabindex="-1"><a class="header-anchor" href="#获取rn-js线程并得到线程cpu时间" aria-hidden="true">#</a> 获取RN JS线程并得到线程CPU时间</h1>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token function">getReactApplicationContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getCatalystInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getReactQueueConfiguration</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getJSQueueThread</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">runOnQueue</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Runnable</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token annotation punctuation">@Override</span>
    <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">long</span> cpuTime <span class="token operator">=</span> <span class="token class-name">SystemClock</span><span class="token punctuation">.</span><span class="token function">currentThreadTimeMillis</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">long</span> det <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>lastCpuTime <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            det <span class="token operator">=</span> cpuTime <span class="token operator">-</span> lastCpuTime<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        lastCpuTime <span class="token operator">=</span> cpuTime<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h1 id="获取进程内存占用相关数据" tabindex="-1"><a class="header-anchor" href="#获取进程内存占用相关数据" aria-hidden="true">#</a> 获取进程内存占用相关数据</h1>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token comment">// java虚拟机能够从操作系统那里挖到的最大的内存</span>
<span class="token class-name">Runtime</span><span class="token punctuation">.</span><span class="token function">getRuntime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">maxMemory</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment">// java虚拟机现在已经从操作系统那里挖过来的内存大小，也就是java虚拟机这个进程当时所占用的所有 内存</span>
<span class="token class-name">Runtime</span><span class="token punctuation">.</span><span class="token function">getRuntime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">totalMemory</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment">// 从操作系统那里挖过来而又没有用上的内存</span>
<span class="token class-name">Runtime</span><span class="token punctuation">.</span><span class="token function">getRuntime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">freeMemory</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h1 id="获取手机帧数情况" tabindex="-1"><a class="header-anchor" href="#获取手机帧数情况" aria-hidden="true">#</a> 获取手机帧数情况</h1>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token class-name">Choreographer</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">postFrameCallback</span><span class="token punctuation">(</span>mRateRunnable<span class="token punctuation">)</span><span class="token punctuation">;</span>
   <span class="token keyword">private</span> <span class="token keyword">class</span> <span class="token class-name">FrameRateRunnable</span> <span class="token keyword">implements</span> <span class="token class-name">Choreographer<span class="token punctuation">.</span>FrameCallback</span> <span class="token punctuation">{</span>
         <span class="token keyword">private</span> <span class="token keyword">int</span> totalFramesPerSecond<span class="token punctuation">;</span>
     <span class="token annotation punctuation">@Override</span>
     <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">doFrame</span><span class="token punctuation">(</span><span class="token keyword">long</span> frameTimeNanos<span class="token punctuation">)</span> <span class="token punctuation">{</span>
             totalFramesPerSecond<span class="token operator">++</span><span class="token punctuation">;</span>
         <span class="token class-name">Choreographer</span><span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">postFrameCallback</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
     <span class="token punctuation">}</span>
 <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h1 id="eventbus" tabindex="-1"><a class="header-anchor" href="#eventbus" aria-hidden="true">#</a> EventBus</h1>
<p>可参考： https://www.jianshu.com/p/e7d5c7bda783</p>
</template>
