<template><p>UIManger的作用就是讲JS的组件转换为原生组件，为了更好的理解UIManger，我们先看下UIManger的源码,UIManager对应Android的UIManagerModule</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">UIManagerModule</span> <span class="token keyword">extends</span> <span class="token class-name">ReactContextBaseJavaModule</span>
    <span class="token keyword">implements</span> <span class="token class-name">OnBatchCompleteListener</span><span class="token punctuation">,</span> <span class="token class-name">LifecycleEventListener</span><span class="token punctuation">,</span> <span class="token class-name">UIManager</span> <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">UIImplementation</span> mUIImplementation<span class="token punctuation">;</span>
<span class="token annotation punctuation">@ReactMethod</span>
<span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">createView</span><span class="token punctuation">(</span><span class="token keyword">int</span> tag<span class="token punctuation">,</span> <span class="token class-name">String</span> className<span class="token punctuation">,</span> <span class="token keyword">int</span> rootViewTag<span class="token punctuation">,</span> <span class="token class-name">ReadableMap</span> props<span class="token punctuation">)</span> <span class="token punctuation">{</span>
     <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
  mUIImplementation<span class="token punctuation">.</span><span class="token function">createView</span><span class="token punctuation">(</span>tag<span class="token punctuation">,</span> className<span class="token punctuation">,</span> rootViewTag<span class="token punctuation">,</span> props<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token annotation punctuation">@ReactMethod</span>
<span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">updateView</span><span class="token punctuation">(</span><span class="token keyword">int</span> tag<span class="token punctuation">,</span> <span class="token class-name">String</span> className<span class="token punctuation">,</span> <span class="token class-name">ReadableMap</span> props<span class="token punctuation">)</span> <span class="token punctuation">{</span>
     <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
  mUIImplementation<span class="token punctuation">.</span><span class="token function">updateView</span><span class="token punctuation">(</span>tag<span class="token punctuation">,</span> className<span class="token punctuation">,</span> props<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token annotation punctuation">@ReactMethod</span>
<span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">manageChildren</span><span class="token punctuation">(</span>
        <span class="token keyword">int</span> viewTag<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReadableArray</span> moveFrom<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReadableArray</span> moveTo<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReadableArray</span> addChildTags<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReadableArray</span> addAtIndices<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReadableArray</span> removeFrom<span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">}</span>
    mUIImplementation<span class="token punctuation">.</span><span class="token function">manageChildren</span><span class="token punctuation">(</span>
          viewTag<span class="token punctuation">,</span> moveFrom<span class="token punctuation">,</span> moveTo<span class="token punctuation">,</span> addChildTags<span class="token punctuation">,</span> addAtIndices<span class="token punctuation">,</span> removeFrom<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br></div></div><p>前边提到@ReactMethod注解是为了供JS端来调用
UIManagerModule的主要作用是：
1.为JS组件转换为Android端可以识别的View
2.更新View视图
createView
createView的实现是在UIImplementation.java文件中</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">createView</span><span class="token punctuation">(</span><span class="token keyword">int</span> tag<span class="token punctuation">,</span> <span class="token class-name">String</span> className<span class="token punctuation">,</span> <span class="token keyword">int</span> rootViewTag<span class="token punctuation">,</span> <span class="token class-name">ReadableMap</span> props<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">synchronized</span> <span class="token punctuation">(</span>uiImplementationThreadLock<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token class-name">ReactShadowNode</span> cssNode <span class="token operator">=</span> <span class="token function">createShadowNode</span><span class="token punctuation">(</span>className<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name">ReactShadowNode</span> rootNode <span class="token operator">=</span> mShadowNodeRegistry<span class="token punctuation">.</span><span class="token function">getNode</span><span class="token punctuation">(</span>rootViewTag<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name">Assertions</span><span class="token punctuation">.</span><span class="token function">assertNotNull</span><span class="token punctuation">(</span>rootNode<span class="token punctuation">,</span> <span class="token string">"Root node with tag "</span> <span class="token operator">+</span> rootViewTag <span class="token operator">+</span> <span class="token string">" doesn't exist"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    cssNode<span class="token punctuation">.</span><span class="token function">setReactTag</span><span class="token punctuation">(</span>tag<span class="token punctuation">)</span><span class="token punctuation">;</span>
    cssNode<span class="token punctuation">.</span><span class="token function">setViewClassName</span><span class="token punctuation">(</span>className<span class="token punctuation">)</span><span class="token punctuation">;</span>
    cssNode<span class="token punctuation">.</span><span class="token function">setRootTag</span><span class="token punctuation">(</span>rootNode<span class="token punctuation">.</span><span class="token function">getReactTag</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    cssNode<span class="token punctuation">.</span><span class="token function">setThemedContext</span><span class="token punctuation">(</span>rootNode<span class="token punctuation">.</span><span class="token function">getThemedContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    mShadowNodeRegistry<span class="token punctuation">.</span><span class="token function">addNode</span><span class="token punctuation">(</span>cssNode<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token class-name">ReactStylesDiffMap</span> styles <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>props <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
          styles <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ReactStylesDiffMap</span><span class="token punctuation">(</span>props<span class="token punctuation">)</span><span class="token punctuation">;</span>
      cssNode<span class="token punctuation">.</span><span class="token function">updateProperties</span><span class="token punctuation">(</span>styles<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token function">handleCreateView</span><span class="token punctuation">(</span>cssNode<span class="token punctuation">,</span> rootViewTag<span class="token punctuation">,</span> styles<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">protected</span> <span class="token keyword">void</span> <span class="token function">handleCreateView</span><span class="token punctuation">(</span>
        <span class="token class-name">ReactShadowNode</span> cssNode<span class="token punctuation">,</span>
    <span class="token keyword">int</span> rootViewTag<span class="token punctuation">,</span>
    <span class="token annotation punctuation">@Nullable</span> <span class="token class-name">ReactStylesDiffMap</span> styles<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>cssNode<span class="token punctuation">.</span><span class="token function">isVirtual</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        mNativeViewHierarchyOptimizer<span class="token punctuation">.</span><span class="token function">handleCreateView</span><span class="token punctuation">(</span>cssNode<span class="token punctuation">,</span> cssNode<span class="token punctuation">.</span><span class="token function">getThemedContext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> styles<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
 <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token keyword">class</span> <span class="token class-name">LayoutUpdateFinishedOperation</span> <span class="token keyword">implements</span> <span class="token class-name">UIOperation</span> <span class="token punctuation">{</span>
    <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
  <span class="token keyword">private</span> <span class="token class-name">LayoutUpdateFinishedOperation</span><span class="token punctuation">(</span><span class="token class-name">ReactShadowNode</span> node<span class="token punctuation">,</span> <span class="token class-name">UIImplementation<span class="token punctuation">.</span>LayoutUpdateListener</span> listener<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        mNode <span class="token operator">=</span> node<span class="token punctuation">;</span>
    mListener <span class="token operator">=</span> listener<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token annotation punctuation">@Override</span>
  <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">execute</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        mListener<span class="token punctuation">.</span><span class="token function">onLayoutUpdated</span><span class="token punctuation">(</span>mNode<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>​
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br></div></div></template>
