<template><h1 id="启动应用默认-activity" tabindex="-1"><a class="header-anchor" href="#启动应用默认-activity" aria-hidden="true">#</a> 启动应用默认 activity</h1>
<p>场景来源：推送处理 Activity</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">launchAppWithData</span><span class="token punctuation">(</span><span class="token class-name">Context</span> context<span class="token punctuation">,</span> <span class="token class-name">String</span> <span class="token class-name">PushMsg</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token class-name">Intent</span> intent <span class="token operator">=</span> context<span class="token punctuation">.</span><span class="token function">getPackageManager</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getLaunchIntentForPackage</span><span class="token punctuation">(</span>context<span class="token punctuation">.</span><span class="token function">getPackageName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>intent <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    intent<span class="token punctuation">.</span><span class="token function">putExtra</span><span class="token punctuation">(</span><span class="token string">"PushMsg"</span><span class="token punctuation">,</span> <span class="token class-name">PushMsg</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    intent<span class="token punctuation">.</span><span class="token function">setFlags</span><span class="token punctuation">(</span><span class="token class-name">Intent</span><span class="token punctuation">.</span>FLAG_ACTIVITY_NEW_TASK <span class="token operator">|</span> <span class="token class-name">Intent</span><span class="token punctuation">.</span>FLAG_ACTIVITY_SINGLE_TOP <span class="token operator">|</span> <span class="token class-name">Intent</span><span class="token punctuation">.</span>FLAG_ACTIVITY_CLEAR_TOP<span class="token punctuation">)</span><span class="token punctuation">;</span>
    context<span class="token punctuation">.</span><span class="token function">startActivity</span><span class="token punctuation">(</span>intent<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h1 id="读取-asset" tabindex="-1"><a class="header-anchor" href="#读取-asset" aria-hidden="true">#</a> 读取 Asset</h1>
<ul>
<li>??不能直接获取 asset 路径</li>
</ul>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">getAssetFilePath</span><span class="token punctuation">(</span>context<span class="token operator">:</span> Context<span class="token punctuation">,</span> fileName<span class="token operator">:</span> String<span class="token punctuation">)</span><span class="token operator">:</span> String<span class="token operator">?</span> <span class="token punctuation">{</span>
            <span class="token keyword">val</span> cacheFile <span class="token operator">=</span> <span class="token function">File</span><span class="token punctuation">(</span>context<span class="token punctuation">.</span>cacheDir<span class="token punctuation">,</span> fileName<span class="token punctuation">)</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>cacheFile<span class="token punctuation">.</span><span class="token function">exists</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span> cacheFile<span class="token punctuation">.</span>absolutePath
            <span class="token keyword">if</span> <span class="token punctuation">(</span>TextUtils<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span>fileName<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token keyword">null</span>
            <span class="token keyword">try</span> <span class="token punctuation">{</span>
                context<span class="token punctuation">.</span>assets<span class="token punctuation">.</span><span class="token function">open</span><span class="token punctuation">(</span>fileName<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">use</span> <span class="token punctuation">{</span> inS <span class="token operator">-></span>
                    <span class="token keyword">val</span> outputStream <span class="token operator">=</span> <span class="token function">FileOutputStream</span><span class="token punctuation">(</span>cacheFile<span class="token punctuation">)</span>
                    outputStream<span class="token punctuation">.</span><span class="token function">use</span> <span class="token punctuation">{</span> outS <span class="token operator">-></span>
                        <span class="token keyword">val</span> buf <span class="token operator">=</span> <span class="token function">ByteArray</span><span class="token punctuation">(</span><span class="token number">1024</span><span class="token punctuation">)</span>
                        <span class="token keyword">var</span> len<span class="token operator">:</span> Int
                        <span class="token keyword">while</span> <span class="token punctuation">(</span>inS<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span>buf<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">also</span> <span class="token punctuation">{</span> len <span class="token operator">=</span> it <span class="token punctuation">}</span> <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                            outS<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>buf<span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> len<span class="token punctuation">)</span>
                        <span class="token punctuation">}</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token operator">:</span> Exception<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                Log<span class="token punctuation">.</span><span class="token function">e</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"AssetUtils"</span></span><span class="token punctuation">,</span> <span class="token string-literal singleline"><span class="token string">"读取Asset[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">fileName</span></span><span class="token string">]失败"</span></span><span class="token punctuation">)</span>
                e<span class="token punctuation">.</span><span class="token function">printStackTrace</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
                <span class="token keyword">return</span> <span class="token keyword">null</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">return</span> cacheFile<span class="token punctuation">.</span>absolutePath
        <span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div></template>
