<template><h1 id="嵌套类与内部类" tabindex="-1"><a class="header-anchor" href="#嵌套类与内部类" aria-hidden="true">#</a> <a href="https://book.kotlincn.net/text/nested-classes.html" target="_blank" rel="noopener noreferrer">嵌套类与内部类<ExternalLinkIcon/></a></h1>
<p>可以将接口嵌套在类中、将类嵌套在接口中、将接口嵌套在接口中</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">class</span> Outer <span class="token punctuation">{</span>
    <span class="token keyword">private</span> <span class="token keyword">val</span> bar<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">1</span>
    <span class="token keyword">class</span> Nested <span class="token punctuation">{</span>
        <span class="token keyword">fun</span> <span class="token function">foo</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token number">2</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">val</span> demo <span class="token operator">=</span> Outer<span class="token punctuation">.</span><span class="token function">Nested</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">foo</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token comment">// == 2</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h1 id="枚举类" tabindex="-1"><a class="header-anchor" href="#枚举类" aria-hidden="true">#</a> <a href="https://book.kotlincn.net/text/enum-classes.html" target="_blank" rel="noopener noreferrer">枚举类<ExternalLinkIcon/></a></h1>
<p>因为每一个枚举都是枚举类的实例，所以可以这样初始化：</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">enum</span> <span class="token keyword">class</span> <span class="token function">Color</span><span class="token punctuation">(</span><span class="token keyword">val</span> rgb<span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">RED</span><span class="token punctuation">(</span><span class="token number">0xFF0000</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">GREEN</span><span class="token punctuation">(</span><span class="token number">0x00FF00</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">BLUE</span><span class="token punctuation">(</span><span class="token number">0x0000FF</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>枚举常量可以声明其带有相应方法以及覆盖了基类方法的自身匿名类 。</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">enum</span> <span class="token keyword">class</span> ProtocolState <span class="token punctuation">{</span>
    WAITING <span class="token punctuation">{</span>
        <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">signal</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> TALKING
    <span class="token punctuation">}</span><span class="token punctuation">,</span>

    TALKING <span class="token punctuation">{</span>
        <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">signal</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span> WAITING
    <span class="token punctuation">}</span><span class="token punctuation">;</span>

    <span class="token keyword">abstract</span> <span class="token keyword">fun</span> <span class="token function">signal</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> ProtocolState
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="在枚举类中实现接口" tabindex="-1"><a class="header-anchor" href="#在枚举类中实现接口" aria-hidden="true">#</a> 在枚举类中实现接口</h2>
<p>一个枚举类可以实现接口（但不能从类继承），可以为所有条目提供统一的接口成员实现，也可以在相应匿名类中为每个条目提供各自的实现。 只需将想要实现的接口添加到枚举类声明中即可，如下所示：</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">import</span> java<span class="token punctuation">.</span>util<span class="token punctuation">.</span>function<span class="token punctuation">.</span>BinaryOperator
<span class="token keyword">import</span> java<span class="token punctuation">.</span>util<span class="token punctuation">.</span>function<span class="token punctuation">.</span>IntBinaryOperator

<span class="token comment">//sampleStart</span>
<span class="token keyword">enum</span> <span class="token keyword">class</span> IntArithmetics <span class="token operator">:</span> BinaryOperator<span class="token operator">&lt;</span>Int<span class="token operator">></span><span class="token punctuation">,</span> IntBinaryOperator <span class="token punctuation">{</span>
    PLUS <span class="token punctuation">{</span>
        <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">apply</span><span class="token punctuation">(</span>t<span class="token operator">:</span> Int<span class="token punctuation">,</span> u<span class="token operator">:</span> Int<span class="token punctuation">)</span><span class="token operator">:</span> Int <span class="token operator">=</span> t <span class="token operator">+</span> u
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    TIMES <span class="token punctuation">{</span>
        <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">apply</span><span class="token punctuation">(</span>t<span class="token operator">:</span> Int<span class="token punctuation">,</span> u<span class="token operator">:</span> Int<span class="token punctuation">)</span><span class="token operator">:</span> Int <span class="token operator">=</span> t <span class="token operator">*</span> u
    <span class="token punctuation">}</span><span class="token punctuation">;</span>

    <span class="token keyword">override</span> <span class="token keyword">fun</span> <span class="token function">applyAsInt</span><span class="token punctuation">(</span>t<span class="token operator">:</span> Int<span class="token punctuation">,</span> u<span class="token operator">:</span> Int<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token function">apply</span><span class="token punctuation">(</span>t<span class="token punctuation">,</span> u<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
<span class="token comment">//sampleEnd</span>

<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">val</span> a <span class="token operator">=</span> <span class="token number">13</span>
    <span class="token keyword">val</span> b <span class="token operator">=</span> <span class="token number">31</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span>f <span class="token keyword">in</span> IntArithmetics<span class="token punctuation">.</span><span class="token function">values</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">f</span></span><span class="token string">(</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">a</span></span><span class="token string">, </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">b</span></span><span class="token string">) = </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">f<span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">)</span></span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div></template>
