<template><h1 id="解构声明" tabindex="-1"><a class="header-anchor" href="#解构声明" aria-hidden="true">#</a> <a href="https://book.kotlincn.net/text/destructuring-declarations.html" target="_blank" rel="noopener noreferrer">解构声明<ExternalLinkIcon/></a></h1>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> <span class="token punctuation">(</span>name<span class="token punctuation">,</span> age<span class="token punctuation">)</span> <span class="token operator">=</span> person
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>⚠️：name、age 并不是 person 属性名 ??①</p>
<p>一个解构声明会被编译成以下代码</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> name <span class="token operator">=</span> person<span class="token punctuation">.</span><span class="token function">component1</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">val</span> age <span class="token operator">=</span> person<span class="token punctuation">.</span><span class="token function">component2</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>任何表达式都可以出现在解构声明的右侧，只要可以对它调用所需数量的 component 函数即可</p>
<h2 id="在-lambda-表达式中解构" tabindex="-1"><a class="header-anchor" href="#在-lambda-表达式中解构" aria-hidden="true">#</a> 在 lambda 表达式中解构</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code>map<span class="token punctuation">.</span><span class="token function">mapValues</span> <span class="token punctuation">{</span> entry <span class="token operator">-></span> <span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">entry<span class="token punctuation">.</span>value</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">!"</span></span> <span class="token punctuation">}</span>
map<span class="token punctuation">.</span><span class="token function">mapValues</span> <span class="token punctuation">{</span> <span class="token punctuation">(</span>key<span class="token punctuation">,</span> value<span class="token punctuation">)</span> <span class="token operator">-></span> <span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">value</span></span><span class="token string">!"</span></span> <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>注意和普通的参数区别</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token punctuation">{</span> a <span class="token comment">//-> …… } // 一个参数</span>
<span class="token punctuation">{</span> a<span class="token punctuation">,</span> b <span class="token comment">//-> …… } // 两个参数</span>
<span class="token punctuation">{</span> <span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">)</span> <span class="token comment">//-> …… } // 一个解构对</span>
<span class="token punctuation">{</span> <span class="token punctuation">(</span>a<span class="token punctuation">,</span> b<span class="token punctuation">)</span><span class="token punctuation">,</span> c <span class="token comment">//-> …… } // 一个解构对以及其他参数</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h1 id="question-list" tabindex="-1"><a class="header-anchor" href="#question-list" aria-hidden="true">#</a> question list</h1>
<ul>
<li>??①: 被解构的类属性换个顺序，结构出来的结果就不对了？</li>
</ul>
</template>
