<template><h1 id="数据类" tabindex="-1"><a class="header-anchor" href="#数据类" aria-hidden="true">#</a> <a href="https://book.kotlincn.net/text/data-classes.html" target="_blank" rel="noopener noreferrer">数据类<ExternalLinkIcon/></a></h1>
<p>只保存数据的类</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">User</span><span class="token punctuation">(</span><span class="token keyword">val</span> name<span class="token operator">:</span> String<span class="token punctuation">,</span> <span class="token keyword">val</span> age<span class="token operator">:</span> Int<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="在类体中声明的属性" tabindex="-1"><a class="header-anchor" href="#在类体中声明的属性" aria-hidden="true">#</a> 在类体中声明的属性</h2>
<p>自动生成的函数，编译器只使用在主构造函数内部定义的属性，如需在生成的实现中排除一个属性，请将其声明在类体中：</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Person</span><span class="token punctuation">(</span><span class="token keyword">val</span> name<span class="token operator">:</span> String<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> age<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">0</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Person</span><span class="token punctuation">(</span><span class="token keyword">val</span> name<span class="token operator">:</span> String<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> age<span class="token operator">:</span> Int <span class="token operator">=</span> <span class="token number">0</span>
<span class="token punctuation">}</span>
<span class="token keyword">fun</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">val</span> person1 <span class="token operator">=</span> <span class="token function">Person</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"John"</span></span><span class="token punctuation">)</span>
    <span class="token keyword">val</span> person2 <span class="token operator">=</span> <span class="token function">Person</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"John"</span></span><span class="token punctuation">)</span>
    person1<span class="token punctuation">.</span>age <span class="token operator">=</span> <span class="token number">10</span>
    person2<span class="token punctuation">.</span>age <span class="token operator">=</span> <span class="token number">20</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"person1 == person2: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">person1 <span class="token operator">==</span> person2</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span> <span class="token comment">// true, 视作相等</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"person1 with age </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">person1<span class="token punctuation">.</span>age</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">person1</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
    <span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"person2 with age </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">person2<span class="token punctuation">.</span>age</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token expression">person2</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h2 id="复制" tabindex="-1"><a class="header-anchor" href="#复制" aria-hidden="true">#</a> 复制</h2>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> jack <span class="token operator">=</span> <span class="token function">User</span><span class="token punctuation">(</span>name <span class="token operator">=</span> <span class="token string-literal singleline"><span class="token string">"Jack"</span></span><span class="token punctuation">,</span> age <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">)</span>
<span class="token keyword">val</span> olderJack <span class="token operator">=</span> jack<span class="token punctuation">.</span><span class="token function">copy</span><span class="token punctuation">(</span>age <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="数据类与解构声明" tabindex="-1"><a class="header-anchor" href="#数据类与解构声明" aria-hidden="true">#</a> 数据类与解构声明</h2>
<p>为数据类生成的 component 函数 使它们可在解构声明(??①)中使用</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">val</span> jane <span class="token operator">=</span> <span class="token function">User</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"Jane"</span></span><span class="token punctuation">,</span> <span class="token number">35</span><span class="token punctuation">)</span>
<span class="token keyword">val</span> <span class="token punctuation">(</span>name<span class="token punctuation">,</span> age<span class="token punctuation">)</span> <span class="token operator">=</span> jane
<span class="token function">println</span><span class="token punctuation">(</span><span class="token string-literal singleline"><span class="token string">"</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">name</span></span><span class="token string">, </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">$</span><span class="token expression">age</span></span><span class="token string"> years of age"</span></span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h1 id="密封类" tabindex="-1"><a class="header-anchor" href="#密封类" aria-hidden="true">#</a> <a href="https://www.kotlincn.net/docs/reference/sealed-classes.html" target="_blank" rel="noopener noreferrer">密封类<ExternalLinkIcon/></a></h1>
<p>??②</p>
<p>密封类用来表示受限的类继承结构：当一个值为有限几种的类型、而不能有任何其他类型时。</p>
<p>声明一个密封类，需要在类名前面添加 sealed 修饰符。若有子类，所有子类都必须在与密封类自身相同的文件中声明。</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">sealed</span> <span class="token keyword">class</span> Expr
<span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Const</span><span class="token punctuation">(</span><span class="token keyword">val</span> number<span class="token operator">:</span> Double<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token function">Expr</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">data</span> <span class="token keyword">class</span> <span class="token function">Sum</span><span class="token punctuation">(</span><span class="token keyword">val</span> e1<span class="token operator">:</span> Expr<span class="token punctuation">,</span> <span class="token keyword">val</span> e2<span class="token operator">:</span> Expr<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token function">Expr</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">object</span> NotANumber <span class="token operator">:</span> <span class="token function">Expr</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>一个密封类是自身抽象的，它不能直接实例化并可以有抽象（abstract）成员。</p>
<p>密封类不允许有非-private 构造函数（其构造函数默认为 private）(??③)。</p>
<p>请注意，扩展密封类子类的类（间接继承者）可以放在任何位置，而无需在同一个文件中。</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code><span class="token keyword">fun</span> <span class="token function">eval</span><span class="token punctuation">(</span>expr<span class="token operator">:</span> Expr<span class="token punctuation">)</span><span class="token operator">:</span> Double <span class="token operator">=</span> <span class="token keyword">when</span><span class="token punctuation">(</span>expr<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">is</span> Const <span class="token operator">-></span> expr<span class="token punctuation">.</span>number
    <span class="token keyword">is</span> Sum <span class="token operator">-></span> <span class="token function">eval</span><span class="token punctuation">(</span>expr<span class="token punctuation">.</span>e1<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token function">eval</span><span class="token punctuation">(</span>expr<span class="token punctuation">.</span>e2<span class="token punctuation">)</span>
    NotANumber <span class="token operator">-></span> Double<span class="token punctuation">.</span>NaN
    <span class="token comment">// 不再需要 `else` 子句，因为我们已经覆盖了所有的情况</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="question-list" tabindex="-1"><a class="header-anchor" href="#question-list" aria-hidden="true">#</a> question list</h2>
<ul>
<li>??componentN() 函数 按声明顺序对应于所有属性</li>
<li>??①：解构声明？</li>
<li>？？标准数据类：标准库提供了 Pair 与 Triple 类
<blockquote>
<p>标准库提供了 Pair 与 Triple 类。尽管在很多情况下具名数据类是更好的设计选择， 因为它们通过为属性提供有意义的名称使代码更具可读性。</p>
</blockquote>
</li>
<li>class 与 data class 异同，data class 使用方法似乎和 class 几乎无差别</li>
<li>??②：密封类使用场景举例</li>
<li>??③：构造函数 private:如何创建实例？</li>
</ul>
</template>
